Models/ViewModels/Upload/UploadFile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using GlobalControlAccessor;
using Microsoft.AspNetCore.Http;

namespace hera.Models.ViewModels.Upload
{
    public class UploadFile
    {
        [Required(ErrorMessage = "Please select an Excel file")]
        [FileType("xls|xlsx", ErrorMessage = "Must be an Excel File")]
        [Display(Name = "Import File")]
        public IFormFile File { get; set; }
        public List<Contract_tracking> Contract_tracking { get; set; }
        public List<UploadContracts> UploadContracts { get; set; }
        public List<UploadGRNI> UploadGRNI { get; set; }

        public List<Venus_grni_raw> Venus_grni_raw { get; set; }
        public List<Venus_grni> Venus_grni { get; set; }

        public UploadFile()
        {
            if (Contract_tracking == null)
            {
                Contract_tracking = new List<Contract_tracking>();
            }
            if (UploadContracts == null)
            {
                UploadContracts = new List<UploadContracts>();
            }
            if (Venus_grni_raw == null)
            {
                Venus_grni_raw = new List<Venus_grni_raw>();
            }
        }
    }

    public class UploadContracts
    {
        public string supplier { get; set; }
        public string supplier_ID { get; set; }
        public string direct { get; set; }
        public string commodity_group { get; set; }
        public string supply_category { get; set; }
        public string nzd { get; set; }
        public string contract_ID { get; set; }
        public string expiry_date { get; set; }
        public string buyer { get; set; }
        public string period_coverage { get; set; }
        public string completed_count { get; set; }
        //public string remarks_last_week { get; set; }
        public string remarks_this_week { get; set; }
    }
    public class UploadGRNI
    {
       
        public long ID_Venus_grni_raw { get; set; }
        public string po_type { get; set; }
        public string po_number { get; set; }
        public string po_date { get; set; }
        public string doc_type { get; set; }
        public string doc_number { get; set; }
        public string doc_date { get; set; }
        public string supplier_code { get; set; }
        public string supplier_name { get; set; }
        public string remark { get; set; }
        public string po_currency { get; set; }
        public float amount { get; set; }
        public string unit { get; set; }
      
       // public bool archived { get; set; }
        public string department { get; set; }
        public string vendor { get; set; }
        public string business { get; set; }
        public string pic { get; set; }
        public int po_age { get; set; }
        public string status { get; set; }

        public long pairID_Venus_grni_raw { get; set; }


    }
   
}

Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using hera.Models;
using hera.Models.ViewModels.Upload;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using System.IO;
using System.Threading;
using System.Data;
using System.Reflection;
using System.ComponentModel;
using hera.Models.ViewModels.Venus;

namespace hera.Controllers
{
    public class UploadFileController : Controller
    {
        private readonly KPIContext db;
        public UploadFileController(KPIContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            UploadFile UploadFile = new UploadFile();

            ViewBag.Status = TempData["Status"];
            ViewBag.Message = TempData["Message"];
            return View();
        }
   
        public ActionResult ExportTemplateGRNI()
       {           
                UploadFile UploadFile = new UploadFile();

            UploadFile.UploadGRNI = (from a in db.Venus_grni_raw
                                     join b in db.Venus_grni on a.ID_Venus_grni_raw equals b.ID_Venus_grni
                                     select new UploadGRNI
                                     {

                                         ID_Venus_grni_raw = a.ID_Venus_grni_raw,

                                         po_type = a.po_type,
                                         po_number = a.po_number,
                                         po_date = a.po_date.ToString("dd/MM/yyyy"),
                                         doc_type = a.doc_type,
                                         doc_number = a.doc_number,
                                         doc_date = a.doc_date.ToString("dd/MM/yyyy"),
                                         supplier_code = a.supplier_code,
                                         supplier_name = a.supplier_name,
                                         remark = a.remark,
                                         po_currency = a.po_currency,
                                         amount = a.amount,
                                         unit = a.unit,
                                         pairID_Venus_grni_raw = a.pairID_Venus_grni_raw,
                                         department = b.department.name,
                                         status = b.status,
                                         vendor = b.vendor.name,
                                         business = b.business_unit.name,
                                         po_age = b.po_age,
                                         pic =b.pic



                                     }
                                                  ).OrderBy(ss => ss.ID_Venus_grni_raw).ToList();

            ExcelPackage excel = new ExcelPackage();
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            ExcelWorksheet wsDefault = excel.Workbook.Worksheets.Add("GRNI");

            DataTable dataTable = new DataTable();
            dataTable = GenerateDataTable(UploadFile.UploadGRNI, new UploadGRNI());

            int GeneralRowStartValue = 3;
            int GeneralRowEndValue = GeneralRowStartValue;

            wsDefault.Cells["A1"].LoadFromDataTable(dataTable, true);
            wsDefault.Cells.AutoFitColumns();

            string documentFileType = ".xlsx";
            string fileName = "GRNITemplate" + documentFileType;
            var byteData = excel.GetAsByteArray();
            return File(byteData, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);

        }

        public ActionResult ExportTemplateContracts()
        {
            UploadFile UploadFile = new UploadFile();

            var TempData = db.Contract_tracking.OrderBy(ss => ss.ID_Contract_tracking).ToList();
            var commodity_group = db.Contract_commodity_group.OrderBy(ss => ss.ID_Contract_commodity_group).Select(ss => ss.name).FirstOrDefault();
            var supply_category = db.Contract_supply_category.OrderBy(ss => ss.ID_Contract_supply_category).Select(ss => ss.name).FirstOrDefault();
            var buyer = db.Contract_buyer.OrderBy(ss => ss.ID_Contract_buyer).Select(ss => ss.name).FirstOrDefault();
            var period_coverage = db.Contract_period_coverage.OrderBy(ss => ss.ID_Contract_period_coverage).Select(ss => ss.period).FirstOrDefault();

            UploadFile.UploadContracts = (from a in db.Contract_tracking
                                          select new UploadContracts
                                          {
                                              supplier = a.supplier,
                                              supplier_ID = a.supplier_ID,
                                              direct = a.direct == true ? "Direct" :"Indirect",
                                              commodity_group =  a.commodity_group.name,
                                              supply_category =  a.supply_category.name,
                                              nzd = a.nzd.ToString(),
                                              contract_ID = a.contract_ID,
                                              expiry_date = a.expiry_date.ToString("dd/MM/yyyy"),
                                              buyer =  a.buyer.name ,
                                              period_coverage =  a.period_coverage.period,
                                              completed_count = a.completed_count == true ? "Completed":"Uncompleted",
                                              remarks_this_week = a.remarks_this_week
                                          }).ToList();

            ExcelPackage excel = new ExcelPackage();
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            ExcelWorksheet wsDefault = excel.Workbook.Worksheets.Add("Employee BPJS");

            DataTable dataTable = new DataTable();
            dataTable = GenerateDataTable(UploadFile.UploadContracts, new UploadContracts());

            int GeneralRowStartValue = 3;
            int GeneralRowEndValue = GeneralRowStartValue;

            wsDefault.Cells["A1"].LoadFromDataTable(dataTable, true);
            wsDefault.Cells.AutoFitColumns();

            string documentFileType = ".xlsx";
            string fileName = "ContractsTemplate" + documentFileType;
            var byteData = excel.GetAsByteArray();
            return File(byteData, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        }

        public IActionResult UploadContracts(UploadFile UploadFile)
        {
            try
            {
                IFormFile file = UploadFile.File;
                CancellationToken cancellationToken;

                var stream = new MemoryStream();
                file.CopyToAsync(stream, cancellationToken);

                var package = new ExcelPackage(stream);
                var currentSheet = package.Workbook.Worksheets;
                var worksheet = currentSheet.First();
                var rowCount = worksheet.Dimension.Rows;

                var list = UploadFile.Contract_tracking.ToList();

                for (int row = 2; row <= rowCount; row++)
                {
                    Contract_tracking toInsert = new Contract_tracking();
                    toInsert.supplier = worksheet.Cells[row, 1].Value.ToString().Trim();
                    toInsert.supplier_ID = worksheet.Cells[row, 2].Value.ToString().Trim();
                    toInsert.direct = worksheet.Cells[row, 3].Value.ToString().Trim() == "1" ? true : false;
                    Contract_commodity_group commodity = db.Contract_commodity_group.Where(s => s.name == worksheet.Cells[row, 4].Value.ToString().Trim()).FirstOrDefault();
                    if (commodity == null)
                    {
                        Contract_commodity_group toAdd = new Contract_commodity_group();
                        toAdd.name = worksheet.Cells[row, 4].Value.ToString().Trim();
                        db.Contract_commodity_group.Add(toAdd);
                        db.SaveChanges();
                    }
                    Contract_buyer  buyer = db.Contract_buyer.Where(s => s.name == worksheet.Cells[row, 9].Value.ToString().Trim()).FirstOrDefault();
                    if (buyer == null)
                    {
                        Contract_buyer toAdd = new Contract_buyer();
                        toAdd.name = worksheet.Cells[row, 9].Value.ToString().Trim();
                        db.Contract_buyer.Add(toAdd);
                        db.SaveChanges();
                    }
                    Contract_supply_category supply_category = db.Contract_supply_category.Where(s => s.name == worksheet.Cells[row, 5].Value.ToString().Trim()).FirstOrDefault();
                    if (supply_category == null)
                    {
                        Contract_supply_category toAdd = new Contract_supply_category();
                        toAdd.name = worksheet.Cells[row, 5].Value.ToString().Trim();
                        db.Contract_supply_category.Add(toAdd);
                        db.SaveChanges();
                    }
                    Contract_period_coverage period_coverage = db.Contract_period_coverage.Where(s => s.period == worksheet.Cells[row, 5].Value.ToString().Trim()).FirstOrDefault();
                    if (period_coverage == null)
                    {
                        Contract_period_coverage toAdd = new Contract_period_coverage();
                        toAdd.period = worksheet.Cells[row, 10].Value.ToString().Trim();
                        db.Contract_period_coverage.Add(toAdd);
                        db.SaveChanges();
                    }

Views/UploadFile/Index.cshtml
@model hera.Models.ViewModels.Upload.UploadFile

@{
    ViewBag.Title = "Upload File";
}

@* Start Main Content *@
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Upload File Contract</h4>
                    <a href="@Url.Action("ExportTemplateContracts", "UploadFile")" id="ExportTemplate" title="Export Template Contracts" class="btn btn-sm btn-info">Export Template</a>
                </div>
                <div class="card-body">
                    <form action=UploadFile/UploadContracts method="post" enctype="multipart/form-data">
                        @Html.TextBoxFor(model => model.File, new { @id = "Browse", @type = "file", @style = "border: 1px solid black; padding: 5px;", @accept = ".xls,.xlsx" })
                        <p>
                            <input action="UploadContracts" type="submit" value="Upload" style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;" />
                        </p>
                    </form>
                </div>
            </div>
        </div>
        @*<div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Upload File Venus</h4>
                    </div>
                    <div class="card-body">
                        <form action="/read-file-venus" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="csrfmiddlewaretoken" value="pMFHfZZ2Us8PptZ8jqKXlfp9e8i9CTGbLvEtMeolru60brHPt4xbLpRrVc2mJz9M">
                            <input type="file" title="Upload excel file" name="excel_file" style="border: 1px solid black; padding: 5px;" required="required">
                            <p>
                                <input type="submit" value="Upload" style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;" disabled="disabled">
                            </p>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Upload File Venus OPO</h4>
                    </div>
                    <div class="card-body">
                        <form action="/read-file-opo" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="csrfmiddlewaretoken" value="pMFHfZZ2Us8PptZ8jqKXlfp9e8i9CTGbLvEtMeolru60brHPt4xbLpRrVc2mJz9M">
                            <input type="file" title="Upload csv file" name="csv_file" style="border: 1px solid black; padding: 5px;" required="required">
                            <p>
                                <input type="submit" value="Upload" style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;" disabled="disabled">
                            </p>
                        </form>
                    </div>
                </div>
            </div>*@
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Upload File Venus GRNI</h4>
               
                    <a href="@Url.Action("ExportTemplateGRNI", "UploadFile")" id="ExportTemplate" title="Export Template GRNI" class="btn btn-sm btn-info">Export Template</a>
                </div>
                <div class="card-body">
                <form action=UploadFile/UploadGRNI method="post" enctype="multipart/form-data">

                    @Html.TextBoxFor(model => model.File, new { @id = "Browse", @type = "file", @style = "border: 1px solid black; padding: 5px;", @accept = ".xls,.xlsx", required = "required" })
                    @*<input type="file" title="Upload csv file" name="csv_file" style="border: 1px solid black; padding: 5px;" required="required">*@
                    <p>
                        <input action="UploadGRNI" type="submit" value="Upload" style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;" />
                    </p>
                </form>
            </div>
            </div>
        </div>
        @*<div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Upload File Venus POA</h4>
                    </div>
                    <div class="card-body">
                        <form action="/read-file-poa" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="csrfmiddlewaretoken" value="pMFHfZZ2Us8PptZ8jqKXlfp9e8i9CTGbLvEtMeolru60brHPt4xbLpRrVc2mJz9M">
                            <input type="file" title="Upload csv file" name="csv_file" style="border: 1px solid black; padding: 5px;" required="required">
                            <p>
                                <input type="submit" value="Upload" style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;" disabled="disabled">
                            </p>
                        </form>
                    </div>
                </div>
            </div>*@
    </div>
</div>
@* End Main Content *@

<script type="text/javascript">
    $(document).ready(function () {
        var status = @ViewBag.Status;

        if (status == "1") {
            $.notify({
                // options
                message: 'Success @ViewBag.Message'
            }, {
                // settings
                type: 'success'
            });
        } else if (status == '0') {
            $.notify({
                // options
                message: 'Failed @ViewBag.Message'
            }, {
                // settings
                type: 'danger'
            });
        }
    });

</script>