Controllers/TableVenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using hera.Models;
using hera.Models.ViewModels.Venus;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;

namespace hera.Controllers
{
    public class TableVenusController : Controller
    {
        private readonly KPIContext db;
        public TableVenusController(KPIContext context)
        {
            db = context;
        }

        public IActionResult Index(string potypepass)
        {
            TableVenusGlobalModel TableVenusGlobalModel = new TableVenusGlobalModel();

            TableVenusGlobalModel.POTypeFilterArray = new string[] { };
            if (!String.IsNullOrEmpty(potypepass))
            {
                TableVenusGlobalModel.POTypeFilterArray = JsonConvert.DeserializeObject<string[]>(potypepass);
            }

            TableVenusGlobalModel.POTypeFilter = (from a in db.Venus_po_type
                                                  select new POTypeFilter
                                                  {
                                                      ID_Venus_po_type = a.ID_Venus_po_type,
                                                      name = a.name,
                                                      IsCheckedPOType = true
                                                  }
                                       ).OrderBy(ss => ss.ID_Venus_po_type).ToList();

            TableVenusGlobalModel = Filter(TableVenusGlobalModel);

            ViewBag.Status = TempData["Status"] != null ? TempData["Status"] : 0;
            ViewBag.Message = TempData["Message"] != null ? TempData["Message"] : "NULL";

            return View(TableVenusGlobalModel);
        }

        [HttpGet]
        public IActionResult Input(long? id)
        {
            TableVenusGlobalModel TableVenusGlobalModel = new TableVenusGlobalModel();
            if (id != null && id != 0)
            {
                TableVenusGlobalModel.GNRIInput.Form = "Edit";

                var Venus_grni_raw = (from a in db.Venus_grni_raw
                                      join b in db.Venus_grni on a.ID_Venus_grni_raw equals b.ID_Venus_grni
                                      where a.ID_Venus_grni_raw == id
                                      select new
                                      {
                                          ID_Venus_grni_raw = a.ID_Venus_grni_raw,
                                          amount = a.amount,
                                          po_type = a.po_type,
                                          po_number = a.po_number,
                                          doc_type = a.doc_type,
                                          doc_number = a.doc_number,
                                          doc_date = a.doc_date,
                                          business_unit = b.business_unit.ID_Venus_business_unit,
                                          department = b.department.ID_Venus_department,
                                          vendor = b.vendor.ID_Venus_vendor,

                                          supplier_code = a.supplier_code,
                                          supplier_name = a.supplier_name,
                                          remark = a.remark,
                                          po_currency = a.po_currency,
                                          po_typeID_Venus_po_type = b.po_typeID_Venus_po_type,
                                          unit = a.unit,
                                          minimum = a.batas_bawah,
                                          maksimum = a.batas_atas,
                                          pic = b.pic,

                                      }).FirstOrDefault();

                TableVenusGlobalModel.GNRIInput.department = Convert.ToInt32(Venus_grni_raw.department);
                TableVenusGlobalModel.GNRIInput.vendor = Convert.ToInt32(Venus_grni_raw.vendor);
                TableVenusGlobalModel.GNRIInput.po_type = Venus_grni_raw.po_type;
                TableVenusGlobalModel.GNRIInput.businessunit = Convert.ToInt32(Venus_grni_raw.business_unit);
                TableVenusGlobalModel.GNRIInput.ID_Venus_grni_raw = Venus_grni_raw.ID_Venus_grni_raw;
             
            
                TableVenusGlobalModel.GNRIInput.po_number = Venus_grni_raw.po_number;
                TableVenusGlobalModel.GNRIInput.doc_type = Venus_grni_raw.doc_type;
                TableVenusGlobalModel.GNRIInput.doc_number = Venus_grni_raw.doc_number;
                TableVenusGlobalModel.GNRIInput.doc_date = Venus_grni_raw.doc_date;
                TableVenusGlobalModel.GNRIInput.supplier_code = Venus_grni_raw.supplier_code;
                TableVenusGlobalModel.GNRIInput.supplier_name = Venus_grni_raw.supplier_name;
                TableVenusGlobalModel.GNRIInput.remark = Venus_grni_raw.remark;
                TableVenusGlobalModel.GNRIInput.po_currency = Venus_grni_raw.po_currency;
                TableVenusGlobalModel.GNRIInput.amount = Venus_grni_raw.amount;
                TableVenusGlobalModel.GNRIInput.unit = Venus_grni_raw.unit;
                TableVenusGlobalModel.GNRIInput.pic = Venus_grni_raw.pic;

            }
            else
            {
                TableVenusGlobalModel.GNRIInput = new TableVenusGNRI();
                TableVenusGlobalModel.GNRIInput.Form = "Create";
            }

            #region dropdownlist
            ViewBag.POType = db.Venus_po_type.Select(ss => new { value = ss.name, text = ss.name }).ToList();
            ViewBag.BusinessUnit = db.Venus_business_unit.Select(ss => new { value = ss.ID_Venus_business_unit, text = ss.name }).ToList();
            ViewBag.Department = db.Venus_department.Select(ss => new { value = ss.ID_Venus_department, text = ss.name }).ToList();
            ViewBag.Vendor = db.Venus_vendor.Select(ss => new { value = ss.ID_Venus_vendor, text = ss.name }).ToList();
            var DocType = new List<string>();
            DocType.Add("PV");
            DocType.Add("OV");
            ViewBag.DocType = DocType.Select(ss => new { value = ss, text = ss }).ToList();
            #endregion

            return PartialView("InputPopup", TableVenusGlobalModel);
        }

        [HttpPost]
        public IActionResult Input(TableVenusGlobalModel TableVenusGlobalModel)
        {
            var dbContextTransaction = db.Database.BeginTransaction();

            try
            {
                long? id = TableVenusGlobalModel.GNRIInput.ID_Venus_grni_raw;
                if (id != null && id != 0)
                {
                    Venus_grni_raw toUpdate = db.Venus_grni_raw.Find(id);
                    toUpdate.po_type = TableVenusGlobalModel.GNRIInput.po_type;
                    toUpdate.po_number = TableVenusGlobalModel.GNRIInput.po_number;
                    toUpdate.doc_type = TableVenusGlobalModel.GNRIInput.doc_type;
                    toUpdate.doc_number = TableVenusGlobalModel.GNRIInput.doc_number;
                    toUpdate.doc_date = TableVenusGlobalModel.GNRIInput.doc_date;
                    toUpdate.supplier_code = TableVenusGlobalModel.GNRIInput.supplier_code;
                    toUpdate.supplier_name = TableVenusGlobalModel.GNRIInput.supplier_name;
                    toUpdate.remark = TableVenusGlobalModel.GNRIInput.remark;
                    toUpdate.po_currency = TableVenusGlobalModel.GNRIInput.po_currency;
                    toUpdate.amount = TableVenusGlobalModel.GNRIInput.amount;
                    toUpdate.batas_bawah = TableVenusGlobalModel.GNRIInput.amount - ((float)Math.Abs(0.05 * TableVenusGlobalModel.GNRIInput.amount));
                    toUpdate.batas_atas = TableVenusGlobalModel.GNRIInput.amount + ((float)Math.Abs(0.05 * TableVenusGlobalModel.GNRIInput.amount));
                    toUpdate.pairID_Venus_grni_raw = 0;

                    toUpdate.unit = TableVenusGlobalModel.GNRIInput.unit;

                    dbContextTransaction.Commit();
                    db.Entry(toUpdate).State = EntityState.Modified;
                    db.SaveChanges();
         
                    Venus_grni toUpdate3 = db.Venus_grni.Find(TableVenusGlobalModel.GNRIInput.ID_Venus_grni_raw);
                    var updatePairnya = db.Venus_grni_raw.Where(x => x.pairID_Venus_grni_raw == id).FirstOrDefault();

                    if (updatePairnya != null)
                    {
                        Venus_grni_raw updatePair = db.Venus_grni_raw.Find(updatePairnya.ID_Venus_grni_raw);
                        Venus_grni updatePairgrni = db.Venus_grni.Find(updatePair.ID_Venus_grni_raw);

                        updatePair.pairID_Venus_grni_raw = 0;
                        toUpdate.pairID_Venus_grni_raw = 0;
                        updatePairgrni.status = "open";

                        db.Entry(toUpdate).State = EntityState.Modified;

                        db.Entry(updatePair).State = EntityState.Modified;
                        db.Entry(updatePairgrni).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                    Venus_po_type po_type = Venus_po_type(TableVenusGlobalModel.GNRIInput.po_type.ToString().Trim());
                    Venus_department department = Venus_department(TableVenusGlobalModel.GNRIInput.department.ToString().Trim());
                    Venus_vendor vendor = Venus_vendor(TableVenusGlobalModel.GNRIInput.vendor.ToString().Trim());
                    Venus_business_unit business_unit = Venus_business_unit(TableVenusGlobalModel.GNRIInput.businessunit.ToString().Trim());
                    toUpdate3.po_number = TableVenusGlobalModel.GNRIInput.po_number;
                    toUpdate3.vendor = vendor; 
                    toUpdate3.po_type = po_type;
                    toUpdate3.department = department;
                    toUpdate3.business_unit = business_unit;
                    toUpdate3.status = "open";

Views/TableVenus/AddEmailPopup.cshtml
@model hera.Models.ViewModels.Venus.TableVenusGlobalModel

<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <br />
    <div class="modal-body">
        @using (Html.BeginForm(Model.URLAction, "TableVenus", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.GNRIInput.ID_Venus_grni_raw)
            @Html.HiddenFor(model => model.idAddEmailArray)
            @Html.HiddenFor(model => model.idAddEmailString)
            <div style="width:45%;float:left">
                <h4>@Model.AddEmailMessage </h4>
            </div>
            <div style="width:45%;float:right">
                <br />
                <br />
                <div class="form-group row">
                    <div class="col-sm-3">
                    </div>
                    <div class="col-sm-9">
                        <input type="submit" value="Yes" class="btn btn-primary" />
                        <input type="button" value="No" class="close btn btn-danger" data-dismiss="modal" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $('.datepicker').datepicker();
    $('.inputSpinner').inputSpinner();
</script>

Views/TableVenus/DeletePopup.cshtml
@model hera.Models.ViewModels.Venus.TableVenusGlobalModel

<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <br />
    <div class="modal-body">
        @using (Html.BeginForm(Model.URLAction, "TableVenus", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.GNRIInput.ID_Venus_grni_raw)
            @Html.HiddenFor(model => model.idDeleteArray)
            @Html.HiddenFor(model => model.idDeleteString)
            <div style="width:45%;float:left">
                <h4>@Model.DeleteMessage </h4>
            </div>
            <div style="width:45%;float:right">
                <br />
                <br />
                <div class="form-group row">
                    <div class="col-sm-3">
                    </div>
                    <div class="col-sm-9">
                        <input type="submit" value="Yes" class="btn btn-primary" />
                        <input type="button" value="No" class="close btn btn-danger" data-dismiss="modal" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $('.datepicker').datepicker();
    $('.inputSpinner').inputSpinner();
</script>

Views/TableVenus/InputPopup.cshtml
@model hera.Models.ViewModels.Venus.TableVenusGlobalModel

<div>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4>@Model.GNRIInput.Form Form</h4>
    </div>
    <br />
    <div class="modal-body">
        @using (Html.BeginForm("Input", "TableVenus", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.GNRIInput.ID_Venus_grni_raw)
        <div style="width:45%;float:left">
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("PO Type :")
                </div>
                <div class="col-sm-7">
                    @Html.DropDownListFor(model => model.GNRIInput.po_type, new SelectList(ViewBag.POType, "value", "text"), "select one", new { @class = "form-control btn dropdown-toggle", required = "required" })
                    @*@Html.TextBoxFor(model => model.GNRIInput.po_type, new { @class = "form-control", required = "required", placeholder = "PO Type" })*@

                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("PO Number :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.po_number, new { @class = "form-control",  required = "required", placeholder = "PO Number" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("Doc Type :")
                </div>
                <div class="col-sm-7">
                    @Html.DropDownListFor(model => model.GNRIInput.doc_type, new SelectList(ViewBag.DocType, "value", "text"), new { @class = "form-control btn dropdown-toggle", required = "required" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("Doc Number :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.doc_number, new { @class = "form-control",  required = "required", placeholder = "Doc Number" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("Doc Date :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.doc_date, new { @class = "form-control datepicker", required = "required", placeholder = "Doc Date" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("Supplier Code :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.supplier_code, new { @class = "form-control", required = "required", placeholder = "Supplier Code" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("Supplier Name :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.supplier_name, new { @class = "form-control", required = "required", placeholder = "Supplier Name" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("Unit :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.unit, new { @class = "form-control",  required = "required", placeholder = "Unit" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    @Html.Label("PIC :")
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.GNRIInput.pic, new { @class = "form-control", required = "required", placeholder = "PIC" })
                </div>
            </div>
        </div>
            <div style="width:45%;float:right">
                <div class="form-group row">
                    <div class="col-sm-5">
                        @Html.Label("Business Unit :")
                    </div>
                    <div class="col-sm-7">
                     
                            @Html.DropDownListFor(model => model.GNRIInput.businessunit, new SelectList(ViewBag.BusinessUnit, "value", "text"), "select one", new { @class = "form-control btn dropdown-toggle", required = "required", })
                      
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        @Html.Label("Vendor :")
                    </div>
                    <div class="col-sm-7">
                     
                            @Html.DropDownListFor(model => model.GNRIInput.vendor, new SelectList(ViewBag.Vendor, "value", "text"), "select one", new { @class = "form-control btn dropdown-toggle", required = "required", })



                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        @Html.Label("User :")
                    </div>
                    <div class="col-sm-7">
                         @Html.DropDownListFor(model => model.GNRIInput.department, new SelectList(ViewBag.Department, "value", "text"), "select one", new { @class = "form-control btn dropdown-toggle", required = "required", })
                      

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        @Html.Label("Remarks :")
                    </div>
                    <div class="col-sm-7">
                        @Html.TextBoxFor(model => model.GNRIInput.remark, new { @class = "form-control", required = "required", placeholder = "Remarks" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        @Html.Label("PO Currency :")
                    </div>
                    <div class="col-sm-7">
                        @Html.TextBoxFor(model => model.GNRIInput.po_currency, new { @class = "form-control", required = "required", placeholder = "PO Currency" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-5">
                        @Html.Label("Amount :")
                    </div>
                    <div class="col-sm-7">
                        @Html.TextBoxFor(model => model.GNRIInput.amount, new { @class = "form-control inputSpinner", required = "required", type = "number", placeholder = "Amount" })
                    </div>
                </div>

                <br />
                <div class="form-group row">
                    <div class="col-sm-7">
                    </div>
                    <div class="col-sm-5">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
                        }
    </div>
</div>

<script type="text/javascript">
    $('.datepicker').datepicker();
    $('.inputSpinner').inputSpinner();
</script>